version: '3'
services:
    mercure:
        image: dunglas/mercure
        environment:
            # You should definitely change all these values in production
            - JWT_KEY=meSt4r4mbul4nc3smeSt4r4mbul4nc3s
            - DEMO=1
            - ALLOW_ANONYMOUS=1
            - HEARTBEAT_INTERVAL=30s
            - ADDR=:3000
            - CORS_ALLOWED_ORIGINS=*
            - PUBLISH_ALLOWED_ORIGINS=http://mercure:3000,http://localhost:3000
        ports:
            - "3000:3000"

